# Generated by Django 5.1.7 on 2025-12-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("PAID", "PAID")],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("PAYMENT", "PAYMENT"), ("FINE", "FINE")], max_length=10
            ),
        ),
    ]
